export const FETCH_ALL_ITEMS = "FETCH_ALL_ITEMS";
export const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
export const SET_COMMON_PRICE = "SET_COMMON_PRICE";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const MINUS_ITEM = "MINUS_ITEM";
export const UPDATE_SEARCH_ITEMS = "UPDATE_SEARCH_ITEMS";
export const UPDATE_SEARCH_FIELD = "UPDATE_SEARCH_FIELD";